#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

#
# RED_STOP
# Отправляет на локальный сокет команду выключения красной лампы
# 23.08.2016
# author S.Ivakhov <nextiter@gmail.com>
#

import socket

SERVER_HOST = '127.0.0.1'
PORT = 9090

client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client_socket.connect((SERVER_HOST, PORT))
client_socket.sendall('stop_red')
client_socket.close()
